---
title: explore-project-template
hero_image: images/banner.png
description: explore-project-template description
version: 1
listed: false
copyedit: false
last_tested: '2025-01-01'
steps:
- title: What you will make
- title: Step title
- title: Step title
- title: Step title
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Challenge
- title: What can you do now?